[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["crates", "assets", "index.html", "frontend/src"]

[serve]
address = "127.0.0.1"
port = 8080

[[hooks]]
stage = "pre_build"
command = "bun"
command_arguments = ["build", "frontend/src/main.tsx", "--outdir", "frontend/dist", "--minify", "--target", "browser"]
